dist: trusty
sudo: required
language: java
install: true
jdk: oraclejdk8

before_install:
#  - sudo apt-get update
  - sudo apt-get install opam
  
script:
 - chmod 777 infer.sh
 - ./infer.sh
 - mvn clean install
 #- infer -- mvn package -Pdev
 