dist: trusty
sudo: required
language: java
#jdk: oraclejdk7

#addons:
#  apt:
#    packages:

#before_install:
#  - sudo apt-get update
#  - sudo apt-get --yes --force-yes install opam
#  - opam init
  
script:
 - curl https://github.com/facebook/infer/releases/download/v0.15.0/infer-linux64-v0.15.0.tar.xz | tar -xf
 - export PATH=`pwd`/infer/bin:$PATH
# - chmod 777 infer.sh
# - ./infer.sh
 - mvn clean install
 - infer run target/*
 #- infer -- mvn package -Pdev
 